# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        
    - name: Build and Test Eureka Service
      run: |
        cd nasaappBackend/nasaAppEurekaService
        ./mvnw clean install

    - name: Build and Test Config Server
      run: |
        cd nasaappBackend/nasaAppConfigServer
        ./mvnw clean install

    - name: Build and Test Api Gateway
      run: |
        cd nasaappBackend/nasaApiGateway
        ./mvnw clean install
        
    - name: Build and Test Registration
      run: |
        cd nasaappBackend/registration
        ./mvnw clean install

    - name: Build and Test Login
      run: |
        cd nasaappBackend/login
        ./mvnw clean install

    - name: Build and Test Apod
      run: |
        cd nasaappBackend/apod
        ./mvnw clean install

    - name: Build and Test wishlist
      run: |
        cd nasaappBackend/wishlist
        ./mvnw clean install

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
